apiVersion: v1
kind: Service
metadata:
  name: flux-manifest-generator
  labels:
    control-plane: flux-manifest-generator
spec:
  type: ClusterIP
  selector:
    app: flux-manifest-generator
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
